#' Plot Shellfish
#'
#' @description
#' `plot_shellfish` returns a `ggplot2` object with the desired plot specified by the `type` argument.
#' @param results a list of results generated by `shellfishrisks::serve_shellfish`
#' @param type
#' The type of plot to generate, one of
#' * "rvars": plot values from the `pop_rvars` objects
#' * "fst": plot fst outcomes
#' * "popsize": plot the subpopulation sizes
#'
#' @return a `ggplot2` object
#' @export
#'
#' @examples
#' \dontrun{
#'
#' results <- serve_shellfish(batches = c("spam","eggs"))
#'
#' plot_shellfish(results, type = "rpart")
#'
#'
#' }
#'
plot_shellfish <- function(results, type = "rvars") {
  farm_years <- results$pop_rvars %>%
    dplyr::filter(grepl("farm", Subpop))

  farm_years <-
    c(miny = min(farm_years$Year),
      maxy = max(farm_years$Year))

  if (type == "rvars") {
    rvars <- c(
      mfit = "Mean fitness",
      mfit_wild = "Mean fitness (wild)",
      het = "Heterozygosity",
      ar = "Log allelic richness"

    )



    wild_fitness <- results$pop_rvars %>%
      dplyr::filter(grepl("wild", Subpop), Rvar == "mfit") %>%
      dplyr::mutate(Rvar = "mfit_wild")

    results$pop_rvars$Value[results$pop_rvars$Rvar == "ar"] <-
      log(results$pop_rvars$Value[results$pop_rvars$Rvar == "ar"])

    out <- results$pop_rvars %>%
      dplyr::bind_rows(wild_fitness) %>%
      dplyr::filter(Rvar != "popsize") %>%
      ggplot2::ggplot(ggplot2::aes(Year, Value, color = Subpop)) +
      ggplot2::geom_vline(xintercept = farm_years, linetype = 2) +
      ggplot2::geom_point() +
      list(
        if (dplyr::n_distinct(results$pop_rvars$Rep) == 1){

          ggplot2::geom_line()

        } else {
          ggplot2::geom_smooth()
        }
      ) +
      ggplot2::facet_grid(
        Rvar ~ batch,
        switch = "y",
        scales = "free_y",
        labeller =  ggplot2::labeller(batch =  ggplot2::label_both, Rvar = rvars)
      ) +
      shellfishrisks::theme_shellfish() +
      ggplot2::scale_y_continuous(name = "") +
      ggplot2::theme(strip.text.y = ggplot2::element_text(size = 8))

  } else if (type == "fst") {
    rvars <- c(Fst_aL = "Adaptive Fst",
               Fst_nL = "Neutral Fst")


    out <- results$pop_pair_rvars %>%
      dplyr::filter(Rvar != "Fst") %>%
      ggplot2::ggplot(ggplot2::aes(Year, Value, color = Pop_pair, fill = Pop_pair)) +
      ggplot2::geom_vline(xintercept = farm_years, linetype = 2) +
      list(
        if (dplyr::n_distinct(results$pop_rvars$Rep) == 1){

          ggplot2::geom_line()

        } else {
          ggplot2::geom_smooth()
        }
      ) +
      ggplot2::geom_point() +
      ggplot2::facet_grid(
        Rvar ~ batch,
        labeller = ggplot2::labeller(Rvar = rvars, batch = ggplot2::label_both),
        switch = "y"
      ) +
      ggplot2::scale_y_continuous(name = "") +
      shellfishrisks::theme_shellfish()


  } else if (type == "popsize") {

    out <- results$pop_rvars %>%
      dplyr::filter(Rvar == "popsize") %>%
      ggplot2::ggplot(ggplot2::aes(Year, Value, color = Subpop)) +
      ggplot2::geom_vline(xintercept = farm_years, linetype = 2) +
      ggplot2::geom_point() +
      list(
        if (dplyr::n_distinct(results$pop_rvars$Rep) == 1){

          ggplot2::geom_line()

        } else {
          ggplot2::geom_smooth()
        }
      ) +
      ggplot2::facet_wrap(
        ~ batch,
        scales = "free_y",
        labeller =  ggplot2::labeller(batch =  ggplot2::label_both)
      ) +
      shellfishrisks::theme_shellfish() +
      ggplot2::scale_y_continuous(name = "Population size") +
      ggplot2::theme(strip.text.y = ggplot2::element_text(size = 8))


  } else {
    stop("unknown plot type")
  }
  return(out)

}
